version: "3.7"

services:
  models:
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8888:8888"
    volumes:
      - "./:/home"
    command: "jupyter-notebook --no-browser --NotebookApp.token=SecretToken --port 8888 --ip 0.0.0.0 --allow-root"
